### ISSUE TITLE
About the validation set?

### ISSUE THREAD

**Issue by wxjiao** [soujanyaporia/MUStARD#19]
It seems that there is no validation set for model optimization. 
Though I can find the argument of `val_split = 0.1` in the `config.py`  file, I cannot find where it is called to form the validation set in other files.
For the Speaker-dependent setting, I can get the idea of Cross Validation. But for Speaker-independent setting, how would you select the model?

**Comment by bryant1410** [comment]
Hey, sorry for the big delay.

`val_split` is something we don't use anymore. I now removed it.

For the SI setting, you can select the model based on validating in a different group (e.g., "TBBT").
