### ISSUE TITLE
Cannot reproduce the results

### ISSUE THREAD

**Issue by feiyuchen7** [soujanyaporia/MUStARD#20]
Hi
Thank you for your work and code
I tried to reproduce the results shown in th paper but noticed large degradations of performance among all  configs.

For example, I got

     weighted avg      0.574     0.584     0.573       356
for independent T+A

    weighted avg      0.602     0.587     0.589       356
for independent T+V

    Weighted Precision: 0.483  Weighted Recall: 0.472  Weighted F score: 0.472
for dependent T

   Weighted Precision: 0.629  Weighted Recall: 0.626  Weighted F score: 0.626
for dependent T+V

Did I miss anything or could you suggest some training tricks?

Thanks

**Comment by devamanyu** [comment]
Hi, 

Thanks for your interest in our work!

1) Please ensure that the environment (with dependencies) are set up as per our instructions. 
2) We have tried our best to provide accurate hyperparameters in the config file (svm_c). In case step 1 is already ensured and reproductions are not achieved, please try out other svm_c variations.
