### ISSUE TITLE
Regarding Feature vector size.

### ISSUE THREAD

**Issue by dhanushsr** [soujanyaporia/MUStARD#21]
Hi,
I was trying to play around with the data set. But I was confused regarding the shape of the dataset.
I understand that the shape of the feature-vectors for `context` is
`(#samples x #sentences x feature-vector-size)`
But on the other hand this was true only for Text and Visual. I was not sure for audio.
Can you please clarify regarding the same.?

Also I would like to know is there anyway I could get the features word wise?
Thank you.

**Comment by devamanyu** [comment]
Hi, 

Audio pickle might have shuffled dimensions. Kindly check the "Audio related functions" in `data_loader.py` to understand how we arrange the features in the desired dimensions.

Thanks.

**Comment by dhanushsr** [comment]
Hi, 

Thank you for clarification. I have another doubt though. Can you please clarify if you don't mind. 
I noticed that `context` is used only for text and visual features but not audio. Can you reason this?

Thanks.

**Comment by bryant1410** [comment]
We haven't tried context for audio, but you can try. My hypothesis is that, for this way of extracting and using the features, it'd just give noise.
