### ISSUE TITLE
Google Collab Notebook request

### ISSUE THREAD

**Issue by suyashjoshi** [soujanyaporia/MUStARD#22]
Hi,

Please convert the code into a Google Collab notebook and drop a link in the README. Love to play with it but it's not clear what the sizes of dataset and model would be and I have a tiny MBP so would be great to run on Collab.

**Comment by bryant1410** [comment]
Folks, I just added a link to a Google Colab demo in the readme: https://github.com/soujanyaporia/MUStARD/commit/d5e264a1d67321a16c18fac247f90f68d310c418
