### ISSUE TITLE
the audio of raw data

### ISSUE THREAD

**Issue by liziming5353** [soujanyaporia/MUStARD#24]
Why is there no sound in some videos in the data? This means that some data is missing audio.

**Comment by bryant1410** [comment]
Can you point out to example video IDs that miss the audio?

**Comment by liziming5353** [comment]
> Can you point out to example video IDs that miss the audio?

Such as 2_29, 2_96, 2_341 in utterances

**Comment by bryant1410** [comment]
I have just tried these 3 and they do have audio. Maybe it's an issue on your end? Such as a missing audio codec.

**Comment by liziming5353** [comment]
> I have just tried these 3 and they do have audio. Maybe it's an issue on your end? Such as a missing audio codec.

I changed the player and the problem was solved. Thank you!

**Comment by liziming5353** [comment]
> I have just tried these 3 and they do have audio. Maybe it's an issue on your end? Such as a missing audio codec.

But when i use matlab to extract the audio features, the returned features are empty, which are only for the previously mentioned videos.

**Comment by bryant1410** [comment]
I'm sorry but I don't know how this method of extracting audio feature
works! The audio works for those videos (you can check it), so it must be
something else.

**Comment by bryant1410** [comment]
I'm gonna close this issue. Please feel free to write again if you still have issues.
