### ISSUE TITLE
Visual Feature Extraction 

### ISSUE THREAD

**Issue by phoenix-ZY** [soujanyaporia/MUStARD#29]
Hi
Thank you for your work and code
Could I get the context_final data by following the Visual Feature Extraction steps?
It seems that I could only get the features/utterances_final hdf5 data.
Did I miss anything in the process?
Thanks.

**Comment by bryant1410** [comment]
Hey, the path is hardcoded in the files so you have to change it manually to make it work for the context. The paths you need to change are the following (I think these are the only ones):

https://github.com/soujanyaporia/MUStARD/blob/master/visual/save_frames.sh#L8-L9
https://github.com/soujanyaporia/MUStARD/blob/master/visual/dataset.py#L12
https://github.com/soujanyaporia/MUStARD/blob/master/visual/dataset.py#L41

I believe you just need to change "utterances" for "context" and it should all just work to get the context features.

Also, just in case, remember we provide the visual features already extracted/processed: https://drive.google.com/open?id=1Ff1WDObGKqpfbvy7-H1mD8YWvBS-Kf26
